# Generated by Django 4.2.1 on 2023-06-21 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0013_character_is_user_controlled_character_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='need_to_response',
            field=models.ManyToManyField(null=True, related_name='game_state_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_user_controlled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
