# Generated by Django 4.2.1 on 2023-06-22 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0014_gamestate_need_to_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='need_to_response',
            field=models.ManyToManyField(blank=True, null=True, related_name='game_state_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
