# Generated by Django 4.2.1 on 2023-06-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_gamestate_need_to_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='system_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mana',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='shield',
            field=models.IntegerField(blank=True),
        ),
    ]
